apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: din3api
  namespace: '1070658800541'
  selfLink: /apis/serving.knative.dev/v1/namespaces/1070658800541/services/din3api
  uid: 1890fb2f-7f16-4f20-8f17-9c4ebaf2811d
  resourceVersion: AAX4aGy3VZE
  generation: 1
  creationTimestamp: '2023-04-03T06:08:38.858834Z'
  labels:
    cloud.googleapis.com/location: europe-central2
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: t9kaje02@students.oamk.fi
    serving.knative.dev/lastModifier: t9kaje02@students.oamk.fi
    run.googleapis.com/operation-id: a2186c18-c372-4e7a-ab42-3fefe8e1695d
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: din3api-placeholder
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 1070658800541-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/cloudrun/placeholder
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 1
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2023-04-03T06:11:07.794833Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2023-04-03T06:11:07.650073Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2023-04-03T06:11:07.794833Z'
  latestReadyRevisionName: din3api-placeholder
  latestCreatedRevisionName: din3api-placeholder
  traffic:
  - revisionName: din3api-placeholder
    percent: 100
    latestRevision: true
  url: https://din3api-37sqsczq3q-lm.a.run.app
  address:
    url: https://din3api-37sqsczq3q-lm.a.run.app
